# -*- coding: utf-8 -*-
"""TCR ASSIGN-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CNE9b08aAfwEarP-ehCFep2TvM2f4FNr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv("/content/anime_data.csv")

dataset.head()

dataset.shape

dataset.describe()

dataset.eps.describe()

dataset[(dataset['eps']<24) &(dataset.duration.isna())].describe()

dataset_excluding_out=dataset[dataset['eps']<50]

dataset_excluding_out.shape

dataset.isnull()

dataset.describe().T

dataset.drop(columns=['title','description'], axis=1, inplace=True)

dataset.head()

dataset.rating.describe()

dataset.dropna(inplace=True)
dataset.shape

# Example: Histogram of anime ratings
plt.figure(figsize=(10, 6))
sns.histplot(data=dataset, x='rating', bins=30, kde=True)
plt.title('Distribution of Anime Ratings')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

print(dataset['mediaType'].unique())
sns.countplot(x=dataset['mediaType'])

print(dataset['sznOfRelease'].unique())
dataset['sznOfRelease'].value_counts().plot.pie(autopct='dark') #plot pie chart
plt.show()

print(dataset['studio_primary'].unique())



#printing city in the given dataset:
print(dataset['watched'].value_counts())
sns.countplot(x=dataset['watched'])#ploting graph

plt.rcParams['figure.figsize']=(28,8)
plt.bar(dataset['eps'],dataset['duration']);
plt.rcParams.update({'font.size':14});
plt.xlabel('eps');
plt.ylabel('duration');

plt.rcParams['figure.figsize']=(28,8)
plt.bar(dataset['rating'],dataset['votes']);
plt.rcParams.update({'font.size':14});
plt.xlabel('rating');
plt.ylabel('votes');

plt.rcParams['figure.figsize']=(8,8)
plt.bar(dataset['watching'],dataset['dropped']);
plt.rcParams.update({'font.size':12});
plt.xlabel('watching');
plt.ylabel('dropped');

year=dataset['mediaType'].value_counts()
ax=plt.rcParams['figure.figsize']=22,8.27
ax=sns.countplot(x='mediaType',data=dataset)
ax.set_xlabel('Year',fontsize=20)
plt.xticks(rotation=45)
ax.set_ylabel('description',fontsize=20)
ax.set_title('mediaType',fontsize=22)

# Example: Correlation heatmap
correlation_matrix = dataset.corr()
plt.figure(figsize=(10, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()